name: Generate Changelog

on:
  push:
    tags:
      - 'v*'  # 例如 v1.0.0 这样的 tag
  workflow_dispatch:

jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: CHANGELOG.md
          skip-version-file: false
          skip-commit: false
          tag-prefix: "v"

      - name: Push changelog back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update CHANGELOG.md"
          file_pattern: CHANGELOG.md
