name: Publish mod

on:
  push:
    tags:
      - "v*"  # 当推送类似 v1.0.0 的标签时触发
  workflow_dispatch:  # 可选：允许手动触发

jobs:
  Publish-Mod:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle #启用Gradle缓存加快构建
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execution authority
        run: chmod +x ./gradlew

      - name: Extract Mod Version
        id: 'read_properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_version'

      - name: Build Mod
        run: ./gradlew build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar

      - name: Publish to Curseforge and Modrinth
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/*.jar
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: hNnseQ1s
          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 1288509
          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}