name: Build and Release Mod

on:
  push:
    tags:
      - "v*"  # 当推送类似 v1.0.0 的标签时触发
  workflow_dispatch:  # 可选：允许手动触发

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Mod Version
        id: 'read_properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_version'


      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Mod
        run: ./gradlew build



      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/${{steps.read_property.outputs.mod_id}}-${{steps.read_property.mod_version}}.jar